name: on_call
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  authentication_package:
    path: ./packages/authentication_package
  core_package:
    path: ./packages/core_package
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  flutter_web_plugins:
    sdk: flutter
  go_router: ^10.0.0
  pocketbase: ^0.11.0
  webview_flutter: ^4.2.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
